### ISSUE TITLE
sprite does not render when used with AlphaFilter

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [pixijs/picture#22]
I have created 
```
Container (
    child : Sprite (filters: [getBlendFilter(PIXI.BLEND_MODES.OVERLAY)])
    filters : [AlphaFilter(1)]
)
```

In the above case a black image is rendered. 
When I remove the `AlphaFilter` on the container then the sprite is blended with the background. 

In the following image the first image is a container without alpha filter.
second image is a container with alpha filter.
![image](https://user-images.githubusercontent.com/16081083/142625730-0362db65-ff90-448d-931a-26e974d95cfd.png)

**Comment by ivanpopelyshev** [comment]
AlphaFilter creates temporary framebuffer background. its empty. blend filter tries to blend on it, well, you see the result :) If you want this to work - please think about order of operations do you want: push filter, pop filter, when to take the background copy to blend with, e.t.c. . Currently I dont see one that can satisfy you. Also please ask this at https://github.com/pixijs/pixijs/discussions , as i cant support my plugins at the moment.

**Comment by a-c-sreedhar-reddy** [comment]
Thanks @ivanpopelyshev 

I changed the structure to which worked.
```
Container (
    child : Sprite
    filters : [AlphaFilter(1), getBlendFilter(PIXI.BLEND_MODES.OVERLAY)]
)
```

**Comment by ivanpopelyshev** [comment]
I dont get why do you even need AlphaFilter there, you can just `sprite.alpha=0.5`
