### ISSUE TITLE
v4 Release not published on NPM

### ISSUE THREAD

**Issue by rj3d** [pixijs/picture#25]
I'd like to use the v4 release in an offline project, but it has not been published to NPM yet. Could you publish it to NPM? Thanks!

**Comment by ivanpopelyshev** [comment]
4.0.1 , done : ) we have extra blend modes in https://github.com/pixijs/picture/blob/master/src/ShaderParts.ts

**Comment by rj3d** [comment]
Awesome, thanks a ton!
